/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.langla.server.tool;

import com.langla.data.DataCenter;
import com.langla.data.SkillTemplate;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import table.HoverIndex;
import table.TableCustom;

/**
 * @author PKoolVN
 **/
public class frmSkillTemplate extends javax.swing.JFrame {

    /**
     * Creates new form frmSkillTemplate
     */
    public ImageIcon getScaledImage(ImageIcon icon, int w, int h) {
        int nw = icon.getIconWidth();
        int nh = icon.getIconHeight();

        if (icon.getIconWidth() > w) {
            nw = w;
            nh = (nw * icon.getIconHeight()) / icon.getIconWidth();
        }

        if (nh > h) {
            nh = h;
            nw = (icon.getIconWidth() * nh) / icon.getIconHeight();
        }

        return new ImageIcon(icon.getImage().getScaledInstance(nw, nh, Image.SCALE_DEFAULT));
    }
    private TableRowSorter<TableModel> rowSorter;

    public frmSkillTemplate() {
        initComponents();
//        Icon aboutIcon = new ImageIcon("DataImage\\IconClient\\1118.png.png");
//        Icon addIcon = new ImageIcon("DataImage\\IconClient\\11.png.png");
//        Icon copyIcon = new ImageIcon("DataImage\\IconClient\\830.png.png");

//        Object[][] data
//                = {
//                    {aboutIcon, "About"},
//                    {addIcon, "Add"},
//                    {copyIcon, "Copy"},};
        jTable1.setRowHeight(128);

        TableCustom.apply(this, jScrollPane1, TableCustom.TableType.DEFAULT, new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                if (e.getButton() == 1) {
                    int row = jTable1.rowAtPoint(e.getPoint());
                    HoverIndex.gI.setIndex(row);
                    try {

                        updateInfo(DataCenter.gI().SkillTemplate[Integer.parseInt(String.valueOf(jTable1.getValueAt(row, 0)))]);
                    } catch (Exception ẽ) {

                    }
                    jTable1.repaint();
                }
            }

            private void updateInfo(SkillTemplate skillTemplate) {
                frmSkillTemplate.this.jLabel1.setText("<html>" + skillTemplate.toString() + "</html>");
            }
        });
        /*
           public short id;
   public String name;
   public String detail;
   public short levelNeed;
   public byte idChar;
   public byte levelMax;
   public byte type;
   public short idIcon;
         */

        updateItem();
        jTable1.setRowSorter(rowSorter);
       

    }

    public void setColumnWidths(int... widths) {
        TableColumnModel columnModel = this.jTable1.getColumnModel();
        for (int i = 0; i < widths.length; i++) {
            if (i < columnModel.getColumnCount()) {
                if (widths[i] != -1) {
                    columnModel.getColumn(i).setMaxWidth(widths[i]);
                } else {
                    columnModel.getColumn(i).setMaxWidth(1000);
                }
            } else {
                break;
            }
        }
    }

    void updateItem() {
        String[] columnNames = {"Id", "Icon", "Tên Skill"};
        Object[][] data = new Object[DataCenter.gI().SkillTemplate.length][3];
        for (int i = 0; i < data.length; i++) {
            data[i][0] = i;
            data[i][1] = new ImageIcon("data\\pkoolvn\\IconClient\\" + DataCenter.gI().SkillTemplate[i].idIcon + ".png.png");
            data[i][2] = "(" + i + ") " + DataCenter.gI().SkillTemplate[i].name;

        }
        this.jTable1.setModel(new DefaultTableModel(data, columnNames) {

            public Class getColumnClass(int column) {
                return data[0][column].getClass();

            }
        });
        setColumnWidths(50, -1, -1);
        rowSorter
                = new TableRowSorter<>(jTable1.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSkillTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSkillTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSkillTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSkillTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSkillTemplate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
/*

  public short id;
   public String name;
   public String detail;
   public boolean isXepChong;
   public byte gioiTinh;
   public byte type;
   public byte idClass;
   public short idIcon;
   public short levelNeed;
   public int taiPhuNeed;
   public short idMob;
   public short idChar;
 */
